apiVersion: v1
kind: ConfigMap
metadata:
  name: cc-config
  namespace: default
data:
  K8S_SERVER_URL: "https://kubernetes.default.svc"
  K8S_SERVER_AGGREGATOR: "cc-aggregator-service"
  K8S_API_CLUSTER_NAME: "ddsl-fra04"
  K8S_API_CONTEXT_NAME: "ddsl-fra04"
  K8S_API_USER_NAME: "edy.diehl@outlook.fr"